/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import javax.swing.table.DefaultTableModel;
import metodosnumericos.Conversiones;
import metodosnumericos.Errores;
import metodosnumericos.PuntoFlotante;
import metodosnumericos.proErrores;
import metodosnumericos.Biseccion;
import metodosnumericos.Bolzano;
import metodosnumericos.Graficador;
import metodosnumericos.EspMetricos;
import metodosnumericos.SerieTylor;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metodosnumericos.GenPDF;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author pablo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    DefaultTableModel modelo;
    Conversiones Conver = new Conversiones();
    Errores Erro = new Errores();
    PuntoFlotante PuntoF = new PuntoFlotante();
    proErrores proErro = new proErrores();
    Biseccion Bisec = new Biseccion();
    Bolzano Bolza = new Bolzano();
    Graficador Graf = new Graficador();
    EspMetricos Esp = new EspMetricos();
    GenPDF generar = new GenPDF();
    SerieTylor sTylor = new SerieTylor();

    public Main() {
        initComponents();
        LimpiarConver();
        LimpiarErr();
        txtResPfloatBin.setVisible(false);
        txtResPfloatHexa.setVisible(false);
        txtPfloatBin.setVisible(false);
        txtPfloatHexa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloPrincipal = new javax.swing.JLabel();
        Unidades = new javax.swing.JTabbedPane();
        Unidad1 = new javax.swing.JTabbedPane();
        Conversiones = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        ComboBox_CW = new javax.swing.JComboBox<>();
        cajaTxt_CW = new javax.swing.JTextField();
        BotonConver = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        ComboBox_CT = new javax.swing.JComboBox<>();
        LimpiarConver = new javax.swing.JButton();
        labelTxtResConv = new javax.swing.JLabel();
        BotonPDFConver = new javax.swing.JButton();
        PanErrores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajaTxtErrN1 = new javax.swing.JTextField();
        cajaTxtErrN2 = new javax.swing.JTextField();
        btErrAbs = new javax.swing.JButton();
        btErrRe = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtResEa = new javax.swing.JLabel();
        txtResEr = new javax.swing.JLabel();
        btLimErr = new javax.swing.JButton();
        PunFlotante = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cajaTxtPfijoYflota = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btPflota = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtResSigno = new javax.swing.JLabel();
        txtResExBin = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtResMan = new javax.swing.JLabel();
        txtResValDeci = new javax.swing.JLabel();
        txtPfloatBin = new javax.swing.JLabel();
        txtPfloatHexa = new javax.swing.JLabel();
        txtResPfloatBin = new javax.swing.JLabel();
        txtResPfloatHexa = new javax.swing.JLabel();
        btLimPuntoFloat = new javax.swing.JButton();
        GenPDFPuntoFyF = new javax.swing.JButton();
        PropaErrores = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cajaTxtValorProX = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cajaTxtNumIterPro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProErro = new javax.swing.JTable();
        btCalcularProErro = new javax.swing.JButton();
        btLimpiarProErro = new javax.swing.JButton();
        btPDF_PE = new javax.swing.JButton();
        Bolzano = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        FuncionXD = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        cajaTxtInterB = new javax.swing.JTextField();
        cajaTxtInterA = new javax.swing.JTextField();
        cajaTxtFuncion = new javax.swing.JTextField();
        M_Bolzano = new javax.swing.JButton();
        LimpiarMBolza = new javax.swing.JButton();
        btPDF_Bolzano = new javax.swing.JButton();
        Biseccion = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cajaTxtFB = new javax.swing.JTextField();
        cajaTxtBInteA = new javax.swing.JTextField();
        cajaTxtBInteB = new javax.swing.JTextField();
        M_Biseccion = new javax.swing.JButton();
        Limpiar_MBisec = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        RespuestaMB = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btPDF_Biseccion = new javax.swing.JButton();
        EspMetricos = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        cajaTxt_x1 = new javax.swing.JTextField();
        cajaTxt_y1 = new javax.swing.JTextField();
        cajaTxt_x2 = new javax.swing.JTextField();
        cajaTxt_y2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Respuesta_Esp = new javax.swing.JLabel();
        CalcularEsMetricos = new javax.swing.JButton();
        Limpiar_Espacios = new javax.swing.JButton();
        btPDF_EM = new javax.swing.JButton();
        SerieTylor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNTST = new javax.swing.JTextField();
        txtFuncionST = new javax.swing.JTextField();
        txtXST = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RespuestaST = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        RungeKutta = new javax.swing.JPanel();
        Unidad2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 115, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloPrincipal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        TituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPrincipal.setText("METODOS NÚMERICOS");
        jPanel1.add(TituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 0, 444, 62));

        Unidades.setBackground(new java.awt.Color(38, 38, 38));
        Unidades.setForeground(new java.awt.Color(255, 255, 255));

        Unidad1.setBackground(new java.awt.Color(38, 38, 38));
        Unidad1.setForeground(new java.awt.Color(255, 255, 255));

        Conversiones.setBackground(new java.awt.Color(18, 166, 82));
        Conversiones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("INGRESE EL NUMERO A CONVERTIR:");
        Conversiones.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 176, -1, 30));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("CONVERSIONES");
        Conversiones.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 344, 104));

        ComboBox_CW.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Binario", "Hexadecimal", "Octal" }));
        ComboBox_CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CWActionPerformed(evt);
            }
        });
        Conversiones.add(ComboBox_CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 176, 160, 30));
        Conversiones.add(cajaTxt_CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 176, 187, 30));

        BotonConver.setBackground(new java.awt.Color(38, 38, 38));
        BotonConver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonConver.setForeground(new java.awt.Color(255, 255, 255));
        BotonConver.setText("CONVERTIR");
        BotonConver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConverActionPerformed(evt);
            }
        });
        Conversiones.add(BotonConver, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 306, 267, 50));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("EL NUMERO A CONVERTIDO ES :");
        Conversiones.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 232, 217, 46));

        ComboBox_CT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Binario", "Hexadecimal", "Octal" }));
        ComboBox_CT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CTActionPerformed(evt);
            }
        });
        Conversiones.add(ComboBox_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 232, 160, 46));

        LimpiarConver.setBackground(new java.awt.Color(38, 38, 38));
        LimpiarConver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LimpiarConver.setForeground(new java.awt.Color(255, 255, 255));
        LimpiarConver.setText("LIMPIAR");
        LimpiarConver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarConverActionPerformed(evt);
            }
        });
        Conversiones.add(LimpiarConver, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 306, 267, 50));

        labelTxtResConv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTxtResConv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTxtResConv.setText("--");
        Conversiones.add(labelTxtResConv, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 232, 187, 46));

        BotonPDFConver.setBackground(new java.awt.Color(38, 38, 38));
        BotonPDFConver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonPDFConver.setForeground(new java.awt.Color(255, 255, 255));
        BotonPDFConver.setText("PDF");
        BotonPDFConver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPDFConverActionPerformed(evt);
            }
        });
        Conversiones.add(BotonPDFConver, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 388, 268, 50));

        Unidad1.addTab("CONVERSIONES", Conversiones);

        PanErrores.setBackground(new java.awt.Color(18, 166, 82));
        PanErrores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ERRORES");
        PanErrores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 228, 69));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NUMERO 2:");
        PanErrores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 178, 126, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NUMERO 1:");
        PanErrores.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 96, 126, 72));
        PanErrores.add(cajaTxtErrN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 228, 33));
        PanErrores.add(cajaTxtErrN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 228, 32));

        btErrAbs.setBackground(new java.awt.Color(38, 38, 38));
        btErrAbs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btErrAbs.setForeground(new java.awt.Color(255, 255, 255));
        btErrAbs.setText("ERROR ABSOLUTO");
        btErrAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErrAbsActionPerformed(evt);
            }
        });
        PanErrores.add(btErrAbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 266, -1, 38));

        btErrRe.setBackground(new java.awt.Color(38, 38, 38));
        btErrRe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btErrRe.setForeground(new java.awt.Color(255, 255, 255));
        btErrRe.setText("ERROR RELATIVO");
        btErrRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErrReActionPerformed(evt);
            }
        });
        PanErrores.add(btErrRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 266, 192, 38));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("RESULTADOS:");
        PanErrores.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 404, 217, 62));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ERROR ABSOLUTO:");
        PanErrores.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 478, 181, 70));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("ERROR RELATIVO:");
        PanErrores.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 548, 182, 36));

        txtResEa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtResEa.setText("--");
        PanErrores.add(txtResEa, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 478, 154, 61));

        txtResEr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtResEr.setText("--");
        PanErrores.add(txtResEr, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 548, 302, 36));

        btLimErr.setBackground(new java.awt.Color(38, 38, 38));
        btLimErr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimErr.setForeground(new java.awt.Color(255, 255, 255));
        btLimErr.setText("LIMPIAR");
        btLimErr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimErrActionPerformed(evt);
            }
        });
        PanErrores.add(btLimErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 322, 212, 64));

        Unidad1.addTab("ERRORES", PanErrores);

        PunFlotante.setBackground(new java.awt.Color(18, 166, 82));
        PunFlotante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("PUNTO FIJO Y FLOTANTE");
        PunFlotante.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 310, 51));
        PunFlotante.add(cajaTxtPfijoYflota, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 182, 44));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Ingresa el valor:");
        PunFlotante.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 140, 44));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("RESPUESTAS:");
        PunFlotante.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 173, 44));

        btPflota.setBackground(new java.awt.Color(38, 38, 38));
        btPflota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPflota.setForeground(new java.awt.Color(255, 255, 255));
        btPflota.setText("CALCULAR");
        btPflota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPflotaActionPerformed(evt);
            }
        });
        PunFlotante.add(btPflota, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 191, 183, 43));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("SIGNO:");
        PunFlotante.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 80, 50));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("EXPONENTE (BINARIO):");
        PunFlotante.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 200, 50));

        txtResSigno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResSigno.setText("--");
        PunFlotante.add(txtResSigno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 202, 29));

        txtResExBin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResExBin.setText("--");
        PunFlotante.add(txtResExBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 399, 250, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("MANTIZA (BINARIO):");
        PunFlotante.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 190, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("VALOR DECIMAL:");
        PunFlotante.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 520, 150, 30));

        txtResMan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResMan.setText("--");
        PunFlotante.add(txtResMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 340, 44));

        txtResValDeci.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResValDeci.setText("--");
        PunFlotante.add(txtResValDeci, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 207, 44));

        txtPfloatBin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPfloatBin.setText("VALOR BINARIO:");
        PunFlotante.add(txtPfloatBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 140, 50));

        txtPfloatHexa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPfloatHexa.setText("VALOR HEXADECIMAL:");
        PunFlotante.add(txtPfloatHexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 180, 28));

        txtResPfloatBin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResPfloatBin.setText("--");
        PunFlotante.add(txtResPfloatBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 202, 50));

        txtResPfloatHexa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResPfloatHexa.setText("--");
        PunFlotante.add(txtResPfloatHexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 202, 40));

        btLimPuntoFloat.setBackground(new java.awt.Color(38, 38, 38));
        btLimPuntoFloat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimPuntoFloat.setForeground(new java.awt.Color(255, 255, 255));
        btLimPuntoFloat.setText("LIMPIAR");
        btLimPuntoFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimPuntoFloatActionPerformed(evt);
            }
        });
        PunFlotante.add(btLimPuntoFloat, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 191, 170, 43));

        GenPDFPuntoFyF.setBackground(new java.awt.Color(38, 38, 38));
        GenPDFPuntoFyF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GenPDFPuntoFyF.setForeground(new java.awt.Color(255, 255, 255));
        GenPDFPuntoFyF.setText("PDF");
        GenPDFPuntoFyF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenPDFPuntoFyFActionPerformed(evt);
            }
        });
        PunFlotante.add(GenPDFPuntoFyF, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 191, 149, 43));

        Unidad1.addTab("PUNTO FLOTANTE", PunFlotante);

        PropaErrores.setBackground(new java.awt.Color(18, 166, 82));
        PropaErrores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("PROPAGACION DE ERRORES");
        PropaErrores.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 350, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Ingresa el valor de \"X\":");
        PropaErrores.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 86, 231, 20));
        PropaErrores.add(cajaTxtValorProX, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 72, 163, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Ingresa el numero de iteraciones:");
        PropaErrores.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 124, -1, 22));
        PropaErrores.add(cajaTxtNumIterPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 124, 163, -1));

        tableProErro.setBackground(new java.awt.Color(38, 38, 38));
        tableProErro.setForeground(new java.awt.Color(255, 255, 255));
        tableProErro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteracion", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProErro);

        PropaErrores.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 164, 690, 399));

        btCalcularProErro.setBackground(new java.awt.Color(38, 38, 38));
        btCalcularProErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCalcularProErro.setForeground(new java.awt.Color(255, 255, 255));
        btCalcularProErro.setText("CALCULAR");
        btCalcularProErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularProErroActionPerformed(evt);
            }
        });
        PropaErrores.add(btCalcularProErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 593, 171, 41));

        btLimpiarProErro.setBackground(new java.awt.Color(38, 38, 38));
        btLimpiarProErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpiarProErro.setForeground(new java.awt.Color(255, 255, 255));
        btLimpiarProErro.setText("LIMPIAR");
        btLimpiarProErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarProErroActionPerformed(evt);
            }
        });
        PropaErrores.add(btLimpiarProErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 593, 171, 41));

        btPDF_PE.setBackground(new java.awt.Color(38, 38, 38));
        btPDF_PE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPDF_PE.setForeground(new java.awt.Color(255, 255, 255));
        btPDF_PE.setText("PDF");
        btPDF_PE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPDF_PEActionPerformed(evt);
            }
        });
        PropaErrores.add(btPDF_PE, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 593, 171, 41));

        Unidad1.addTab("PROPAGACION ERRORES", PropaErrores);

        Bolzano.setBackground(new java.awt.Color(18, 166, 82));
        Bolzano.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Ingrese el extremo izquierdo del intervalo:");
        Bolzano.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 216, 381, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Ingrese el extremo derecho del intervalo:");
        Bolzano.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 269, 362, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("METODO DE BOLZANO");
        Bolzano.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 270, 82));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Ingrese la función (utilice 'x' como variable):");
        Bolzano.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 166, 381, -1));

        FuncionXD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FuncionXD.setText("--");
        Bolzano.add(FuncionXD, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 511, 243, 75));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("La aproximación de la solución es:");
        Bolzano.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 511, -1, 75));
        Bolzano.add(cajaTxtInterB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 263, 142, 30));

        cajaTxtInterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTxtInterAActionPerformed(evt);
            }
        });
        Bolzano.add(cajaTxtInterA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 143, 30));

        cajaTxtFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTxtFuncionActionPerformed(evt);
            }
        });
        Bolzano.add(cajaTxtFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 143, 30));

        M_Bolzano.setBackground(new java.awt.Color(38, 38, 38));
        M_Bolzano.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_Bolzano.setForeground(new java.awt.Color(255, 255, 255));
        M_Bolzano.setText("INGRESAR DATOS");
        M_Bolzano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BolzanoActionPerformed(evt);
            }
        });
        Bolzano.add(M_Bolzano, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 410, 225, 50));

        LimpiarMBolza.setBackground(new java.awt.Color(38, 38, 38));
        LimpiarMBolza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LimpiarMBolza.setForeground(new java.awt.Color(255, 255, 255));
        LimpiarMBolza.setText("LIMPIAR");
        LimpiarMBolza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarMBolzaActionPerformed(evt);
            }
        });
        Bolzano.add(LimpiarMBolza, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 410, 160, 50));

        btPDF_Bolzano.setBackground(new java.awt.Color(38, 38, 38));
        btPDF_Bolzano.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPDF_Bolzano.setForeground(new java.awt.Color(255, 255, 255));
        btPDF_Bolzano.setText("PDF");
        btPDF_Bolzano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPDF_BolzanoActionPerformed(evt);
            }
        });
        Bolzano.add(btPDF_Bolzano, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 410, 225, 50));

        Unidad1.addTab("BOLZANO", Bolzano);

        Biseccion.setBackground(new java.awt.Color(18, 166, 82));
        Biseccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Ingrese la función:");
        Biseccion.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, 63));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Ingrese el límite inferior del intervalo (a):");
        Biseccion.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 290, 50));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Ingrese el límite superior del intervalo (b):");
        Biseccion.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 310, 62));
        Biseccion.add(cajaTxtFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 129, 60));
        Biseccion.add(cajaTxtBInteA, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 129, 40));
        Biseccion.add(cajaTxtBInteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 129, 40));

        M_Biseccion.setBackground(new java.awt.Color(38, 38, 38));
        M_Biseccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_Biseccion.setForeground(new java.awt.Color(255, 255, 255));
        M_Biseccion.setText("CALCULAR");
        M_Biseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BiseccionActionPerformed(evt);
            }
        });
        Biseccion.add(M_Biseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 166, 50));

        Limpiar_MBisec.setBackground(new java.awt.Color(38, 38, 38));
        Limpiar_MBisec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Limpiar_MBisec.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar_MBisec.setText("LIMPIAR");
        Limpiar_MBisec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_MBisecActionPerformed(evt);
            }
        });
        Biseccion.add(Limpiar_MBisec, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 165, 50));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("La raíz se encuentra en x = ");
        Biseccion.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 535, 225, -1));

        RespuestaMB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RespuestaMB.setText("Respuesta");
        Biseccion.add(RespuestaMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 535, 109, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setText("METODO BISECCION");
        Biseccion.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 260, 70));

        btPDF_Biseccion.setBackground(new java.awt.Color(38, 38, 38));
        btPDF_Biseccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPDF_Biseccion.setForeground(new java.awt.Color(255, 255, 255));
        btPDF_Biseccion.setText("PDF");
        btPDF_Biseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPDF_BiseccionActionPerformed(evt);
            }
        });
        Biseccion.add(btPDF_Biseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 171, 50));

        Unidad1.addTab("BISECCION", Biseccion);

        EspMetricos.setBackground(new java.awt.Color(18, 166, 82));
        EspMetricos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setText("ESPACIOS METRICOS");
        EspMetricos.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 290, 70));

        cajaTxt_x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTxt_x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTxt_x1ActionPerformed(evt);
            }
        });
        EspMetricos.add(cajaTxt_x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 141, 101, 50));

        cajaTxt_y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EspMetricos.add(cajaTxt_y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 245, 105, 53));

        cajaTxt_x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EspMetricos.add(cajaTxt_x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 245, 91, 52));

        cajaTxt_y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTxt_y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTxt_y2ActionPerformed(evt);
            }
        });
        EspMetricos.add(cajaTxt_y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 141, 101, 51));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Ingrese las coordenadas del primer punto:  (");
        EspMetricos.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 140, 309, 50));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText(";");
        EspMetricos.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 140, 41, 50));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText(")");
        EspMetricos.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 140, 43, 50));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Ingrese las coordenadas del segundo punto: (");
        EspMetricos.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 245, 345, 50));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText(";");
        EspMetricos.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 245, 65, 50));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText(")");
        EspMetricos.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 244, 48, 52));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("La distancia entre los dos puntos es:");
        EspMetricos.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 447, 412, 50));
        jLabel42.getAccessibleContext().setAccessibleName("");

        Respuesta_Esp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Respuesta_Esp.setText("--");
        EspMetricos.add(Respuesta_Esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 447, 134, 50));
        Respuesta_Esp.getAccessibleContext().setAccessibleName("");

        CalcularEsMetricos.setBackground(new java.awt.Color(38, 38, 38));
        CalcularEsMetricos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CalcularEsMetricos.setForeground(new java.awt.Color(255, 255, 255));
        CalcularEsMetricos.setText("CALCULAR");
        CalcularEsMetricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularEsMetricosActionPerformed(evt);
            }
        });
        EspMetricos.add(CalcularEsMetricos, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 352, 170, 50));

        Limpiar_Espacios.setBackground(new java.awt.Color(38, 38, 38));
        Limpiar_Espacios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Limpiar_Espacios.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar_Espacios.setText("LIMPIAR");
        Limpiar_Espacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_EspaciosActionPerformed(evt);
            }
        });
        EspMetricos.add(Limpiar_Espacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 352, 170, 50));

        btPDF_EM.setBackground(new java.awt.Color(38, 38, 38));
        btPDF_EM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPDF_EM.setForeground(new java.awt.Color(255, 255, 255));
        btPDF_EM.setText("PDF");
        btPDF_EM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPDF_EMActionPerformed(evt);
            }
        });
        EspMetricos.add(btPDF_EM, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 352, 170, 50));

        Unidad1.addTab("ESPACIOS METRICOS", EspMetricos);

        SerieTylor.setBackground(new java.awt.Color(18, 166, 82));
        SerieTylor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ingresa la función:");
        SerieTylor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ingresa el valor de x para calcular la serie de Taylor:");
        SerieTylor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingresa el número de términos de la serie de Taylor: ");
        SerieTylor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        SerieTylor.add(txtNTST, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 120, -1));
        SerieTylor.add(txtFuncionST, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 120, -1));
        SerieTylor.add(txtXST, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Resultado de la serie de Taylor:");
        SerieTylor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 220, 30));

        RespuestaST.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RespuestaST.setText("--");
        SerieTylor.add(RespuestaST, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 120, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        SerieTylor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 150, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PDF");
        SerieTylor.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 150, 50));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LIMPIAR");
        SerieTylor.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 150, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("SERIE DE TYLOR");
        SerieTylor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        Unidad1.addTab("SERIE DE TYLOR", SerieTylor);

        RungeKutta.setBackground(new java.awt.Color(18, 166, 82));

        javax.swing.GroupLayout RungeKuttaLayout = new javax.swing.GroupLayout(RungeKutta);
        RungeKutta.setLayout(RungeKuttaLayout);
        RungeKuttaLayout.setHorizontalGroup(
            RungeKuttaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        RungeKuttaLayout.setVerticalGroup(
            RungeKuttaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        Unidad1.addTab("RUNGE KUTTA", RungeKutta);

        Unidades.addTab("UNIDAD 1", Unidad1);
        Unidades.addTab("UNIDAD 2", Unidad2);

        jPanel1.add(Unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 784, 766));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btErrReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErrReActionPerformed
        // TODO add your handling code here:
        double err1 = 0, err2 = 0, Ea = 0;
        err2 = Double.parseDouble(cajaTxtErrN2.getText());
        err1 = Double.parseDouble(cajaTxtErrN1.getText());
        Ea = Erro.errAbs(err1, err2);
        txtResEr.setText(String.valueOf(Erro.errRel(Ea, err2)));
    }//GEN-LAST:event_btErrReActionPerformed

    private void btErrAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErrAbsActionPerformed
        // TODO add your handling code here:
        double err1 = 0, err2 = 0;
        err1 = Double.parseDouble(cajaTxtErrN1.getText());
        err2 = Double.parseDouble(cajaTxtErrN2.getText());

        txtResEa.setText(String.valueOf(Erro.errAbs(err1, err2)));

    }//GEN-LAST:event_btErrAbsActionPerformed

    private void btLimErrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimErrActionPerformed
        // TODO add your handling code here:
        LimpiarErr();
    }//GEN-LAST:event_btLimErrActionPerformed

    private void btPflotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPflotaActionPerformed
        // TODO add your handling code here:
        String Pfloat = "";

        Pfloat = cajaTxtPfijoYflota.getText();
        boolean verdad = PuntoF.verficarHexa(Pfloat);

        if (verdad == true) {

            txtResPfloatBin.setVisible(false);
            txtResPfloatHexa.setVisible(false);
            txtPfloatBin.setVisible(false);
            txtPfloatHexa.setVisible(false);

            int PfloatEntero = Integer.parseInt(Pfloat.substring(2), 16);
            int signo = (PfloatEntero >> 31) & 1;
            int exponente = ((PfloatEntero >> 23) & 0xFF);
            int mantisa = PfloatEntero & 0x7FFFFF;

            String mantisaBinaria = String.format("%23s", Integer.toBinaryString(mantisa)).replace(' ', '0');
            String exponenteBinario = String.format("%8s", Integer.toBinaryString(exponente)).replace(' ', '0');

            double valor = Math.pow(-1, signo) * (1 + (mantisa / Math.pow(2, 23))) * Math.pow(2, exponente - 127);

            txtResSigno.setText(String.valueOf(signo));
            txtResExBin.setText(String.valueOf(exponenteBinario));
            txtResMan.setText(String.valueOf(mantisaBinaria));
            txtResValDeci.setText(String.valueOf(valor));

        } else {

            txtResPfloatBin.setVisible(true);
            txtResPfloatHexa.setVisible(true);
            txtPfloatBin.setVisible(true);
            txtPfloatHexa.setVisible(true);

            float ValDeci = 0f;
            ValDeci = Float.parseFloat(cajaTxtPfijoYflota.getText());

            int bits = Float.floatToIntBits(ValDeci);
            int signo = (bits >> 31) & 1;
            int exponente = (bits >> 23) & 0xFF;
            int mantisa = bits & 0x7FFFFF;

            String mantisaBinaria = String.format("%23s", Integer.toBinaryString(mantisa)).replace(' ', '0');
            String exponenteBinario = String.format("%8s", Integer.toBinaryString(exponente)).replace(' ', '0');
            String valorBinario = String.format("%32s", Integer.toBinaryString(bits)).replace(' ', '0');
            String valorHexa = String.format("%8s", Integer.toHexString(bits)).replace(' ', '0').toUpperCase();

            float valor = (float) ((Math.pow(-1, signo) * (1 + (mantisa / Math.pow(2, 23)))) * Math.pow(2, exponente - 127));

            txtResSigno.setText(String.valueOf(signo));
            txtResExBin.setText(String.valueOf(exponenteBinario));
            txtResMan.setText(String.valueOf(mantisaBinaria));
            txtResValDeci.setText(String.valueOf(valor));
            txtResPfloatBin.setText(String.valueOf(valorBinario));
            txtResPfloatHexa.setText(String.valueOf("0X" + valorHexa));
        }


    }//GEN-LAST:event_btPflotaActionPerformed

    private void btLimPuntoFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimPuntoFloatActionPerformed
        // TODO add your handling code here:
        LimpiarPuntoFlotante();
    }//GEN-LAST:event_btLimPuntoFloatActionPerformed

    private void btCalcularProErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularProErroActionPerformed
        // TODO add your handling code here:
        try {
            modelo = (DefaultTableModel) this.tableProErro.getModel();

            String valXproErro = cajaTxtValorProX.getText();
            BigDecimal valBigPro = new BigDecimal(valXproErro);
            int IterProErro = Integer.parseInt(cajaTxtNumIterPro.getText());

            XYDataset data = proErro.createDataset(valBigPro, IterProErro);
            JFreeChart chart = proErro.createChart(data);

            ChartFrame frame = new ChartFrame("PROPAGACION DE ERRORES", chart);
            frame.pack();
            frame.setVisible(true);
            //tabla
            for (int i = 1; i <= IterProErro; i++) {
                BigDecimal numerator = proErro.exp(valBigPro, i);
                BigDecimal denominator = proErro.exp(valBigPro, i).subtract(BigDecimal.ONE);
                BigDecimal result = numerator.divide(denominator, 128, RoundingMode.HALF_UP);

                Object datosProErro[] = new Object[]{i, result.toString()};
                modelo.addRow(datosProErro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"NO HAY DATOS EN EL PROGRAMA");
        }

    }//GEN-LAST:event_btCalcularProErroActionPerformed

    private void btLimpiarProErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarProErroActionPerformed
        // TODO add your handling code here:
        cajaTxtNumIterPro.setText("");
        cajaTxtValorProX.setText("");
        modelo.getDataVector().removeAllElements();
        tableProErro.updateUI();
    }//GEN-LAST:event_btLimpiarProErroActionPerformed

    private void M_BiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BiseccionActionPerformed
        // TODO add your handling code here:
        double InterB_A = Double.parseDouble(cajaTxtBInteA.getText());
        double InterB_B = Double.parseDouble(cajaTxtBInteB.getText());
        String functionStr = cajaTxtFB.getText();

        Function<Double, Double> funcionB;
        funcionB = Bisec.CrearFuncionBis(functionStr);
        double xD = Bisec.findRoot(InterB_A, InterB_B, funcionB);
        Bisec.evaluarFuncion(functionStr, xD);
        RespuestaMB.setText(String.valueOf(Bisec.findRoot(InterB_A, InterB_B, funcionB)));
        Bisec.solveBisection(InterB_A, InterB_B, funcionB);
        Graf.generarGrafica(functionStr, InterB_A, InterB_B);
        Bisec.mostrarGrafica(functionStr,InterB_A, InterB_B, funcionB);
    }//GEN-LAST:event_M_BiseccionActionPerformed

    private void Limpiar_MBisecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_MBisecActionPerformed
        // TODO add your handling code here:
        LimpiarBiseccion();
    }//GEN-LAST:event_Limpiar_MBisecActionPerformed

    private void cajaTxtInterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTxtInterAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTxtInterAActionPerformed

    private void M_BolzanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BolzanoActionPerformed
        // TODO add your handling code here:
        double InterA = Double.parseDouble(cajaTxtInterA.getText());
        double InterB = Double.parseDouble(cajaTxtInterB.getText());
        String funcionString = cajaTxtFuncion.getText();

        Function<Double, Double> funcion;
        funcion = Bolza.CrearFuncion(funcionString);

        double valorX = Bolza.EncontrarAproximacion(funcion, InterA, InterB);
        Bolza.EvaluarFuncion(funcionString,valorX);
        Graf.generarGrafica(funcionString, InterA, InterB);
        FuncionXD.setText(String.valueOf(Bolza.EncontrarAproximacion(funcion, InterA, InterB)));
    }//GEN-LAST:event_M_BolzanoActionPerformed

    private void LimpiarMBolzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarMBolzaActionPerformed
        // TODO add your handling code here:
        LimpiarBolzano();
    }//GEN-LAST:event_LimpiarMBolzaActionPerformed

    private void cajaTxtFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTxtFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTxtFuncionActionPerformed

    private void CalcularEsMetricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularEsMetricosActionPerformed
        // TODO add your handling code here:
        double x1 = Double.parseDouble(cajaTxt_x1.getText());
        double y1 = Double.parseDouble(cajaTxt_y1.getText());
        double x2 = Double.parseDouble(cajaTxt_x2.getText());
        double y2 = Double.parseDouble(cajaTxt_y2.getText());
        Respuesta_Esp.setText(String.valueOf(Esp.calcularDistancia(x1, y1, x2, y2)));
        Esp.generarGrafico(x1, y1, x2, y2);

    }//GEN-LAST:event_CalcularEsMetricosActionPerformed

    private void cajaTxt_y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTxt_y2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTxt_y2ActionPerformed

    private void Limpiar_EspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_EspaciosActionPerformed
        // TODO add your handling code here:
        LimpiarEspMetricos();
    }//GEN-LAST:event_Limpiar_EspaciosActionPerformed

    private void GenPDFPuntoFyFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenPDFPuntoFyFActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = JOptionPane.showInputDialog("Ingresa el nombre del nuevo archivo");
            generar.generar(nombre, cajaTxtPfijoYflota.getText(), txtResSigno.getText(), txtResExBin.getText(), txtResMan.getText(), txtResValDeci.getText());
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_GenPDFPuntoFyFActionPerformed

    private void ComboBox_CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CWActionPerformed

    private void BotonConverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConverActionPerformed
        // TODO add your handling code here:
        String d ="decimal", b ="binario", h ="hexadecimal", o ="octal";
        String tipo1=(String)ComboBox_CW.getSelectedItem();
        String tipo2=(String)ComboBox_CT.getSelectedItem();
        String numero1 = cajaTxt_CW.getText();

        if ( tipo1.equalsIgnoreCase(d)) {
            int number = Integer.parseInt(numero1);
            if ( tipo2.equalsIgnoreCase(b)) {
                labelTxtResConv.setText(String.valueOf(Conver.decimalToBinary(number)));
            } else if (tipo2.equalsIgnoreCase(h)) {
                labelTxtResConv.setText(String.valueOf(Conver.decimalToHexadecimal(number)));
            } else if (tipo2.equalsIgnoreCase(o)) {
                labelTxtResConv.setText(String.valueOf(Conver.decimalToOctal(number)));
            } else if (tipo2.equalsIgnoreCase(d)) {
                labelTxtResConv.setText(numero1);
            }
        } else if (tipo1.equalsIgnoreCase(b)){
            if ( tipo2.equalsIgnoreCase(d)) {
                labelTxtResConv.setText(String.valueOf(Conver.binaryToDecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(h)) {
                labelTxtResConv.setText(String.valueOf(Conver.binaryToHexadecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(o)) {
                labelTxtResConv.setText(String.valueOf(Conver.binaryToOctal(numero1)));
            } else if (tipo2.equalsIgnoreCase(b)) {
                labelTxtResConv.setText(numero1);
            }
        } else if (tipo1.equalsIgnoreCase(h)){
            if ( tipo2.equalsIgnoreCase(d)) {
                labelTxtResConv.setText(String.valueOf(Conver.hexadecimalToDecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(b)) {
                labelTxtResConv.setText(String.valueOf(Conver.hexadecimalToBinary(numero1)));
            } else if (tipo2.equalsIgnoreCase(o)) {
                labelTxtResConv.setText(String.valueOf(Conver.hexadecimalToOctal(numero1)));
            } else if (tipo2.equalsIgnoreCase(h)){
                labelTxtResConv.setText(numero1);
            }
        } else if (tipo1.equalsIgnoreCase(o)){
            if ( tipo2.equalsIgnoreCase(d)) {
                labelTxtResConv.setText(String.valueOf(Conver.octalToDecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(h)) {
                labelTxtResConv.setText(String.valueOf(Conver.octalToHexadecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(b)) {
                labelTxtResConv.setText(String.valueOf(Conver.octalToBinary(numero1)));
            } else if (tipo2.equalsIgnoreCase(o)){
                labelTxtResConv.setText(numero1);
            }
        }

    }//GEN-LAST:event_BotonConverActionPerformed

    private void ComboBox_CTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CTActionPerformed

    private void LimpiarConverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarConverActionPerformed
        // TODO add your handling code here:
        LimpiarConver();
    }//GEN-LAST:event_LimpiarConverActionPerformed

    private void BotonPDFConverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPDFConverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPDFConverActionPerformed

    private void btPDF_PEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPDF_PEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPDF_PEActionPerformed

    private void btPDF_BolzanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPDF_BolzanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPDF_BolzanoActionPerformed

    private void btPDF_BiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPDF_BiseccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPDF_BiseccionActionPerformed

    private void btPDF_EMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPDF_EMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPDF_EMActionPerformed

    private void cajaTxt_x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTxt_x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTxt_x1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String functionStr = txtFuncionST.getText();
        double valX = Double.parseDouble(txtXST.getText());
        int numInte = Integer.parseInt(txtNTST.getText());
        
        sTylor.evaluateFunction(functionStr,valX);
        sTylor.factorial(numInte);
        RespuestaST.setText(String.valueOf(sTylor.calculateCustomTaylorSeries(functionStr,valX,numInte)));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Biseccion;
    private javax.swing.JPanel Bolzano;
    private javax.swing.JButton BotonConver;
    private javax.swing.JButton BotonPDFConver;
    private javax.swing.JButton CalcularEsMetricos;
    private javax.swing.JComboBox<String> ComboBox_CT;
    private javax.swing.JComboBox<String> ComboBox_CW;
    private javax.swing.JPanel Conversiones;
    private javax.swing.JPanel EspMetricos;
    private javax.swing.JLabel FuncionXD;
    private javax.swing.JButton GenPDFPuntoFyF;
    private javax.swing.JButton LimpiarConver;
    private javax.swing.JButton LimpiarMBolza;
    private javax.swing.JButton Limpiar_Espacios;
    private javax.swing.JButton Limpiar_MBisec;
    private javax.swing.JButton M_Biseccion;
    private javax.swing.JButton M_Bolzano;
    private javax.swing.JPanel PanErrores;
    private javax.swing.JPanel PropaErrores;
    private javax.swing.JPanel PunFlotante;
    private javax.swing.JLabel RespuestaMB;
    private javax.swing.JLabel RespuestaST;
    private javax.swing.JLabel Respuesta_Esp;
    private javax.swing.JPanel RungeKutta;
    private javax.swing.JPanel SerieTylor;
    private javax.swing.JLabel TituloPrincipal;
    private javax.swing.JTabbedPane Unidad1;
    private javax.swing.JTabbedPane Unidad2;
    private javax.swing.JTabbedPane Unidades;
    private javax.swing.JButton btCalcularProErro;
    private javax.swing.JButton btErrAbs;
    private javax.swing.JButton btErrRe;
    private javax.swing.JButton btLimErr;
    private javax.swing.JButton btLimPuntoFloat;
    private javax.swing.JButton btLimpiarProErro;
    private javax.swing.JButton btPDF_Biseccion;
    private javax.swing.JButton btPDF_Bolzano;
    private javax.swing.JButton btPDF_EM;
    private javax.swing.JButton btPDF_PE;
    private javax.swing.JButton btPflota;
    private javax.swing.JTextField cajaTxtBInteA;
    private javax.swing.JTextField cajaTxtBInteB;
    private javax.swing.JTextField cajaTxtErrN1;
    private javax.swing.JTextField cajaTxtErrN2;
    private javax.swing.JTextField cajaTxtFB;
    private javax.swing.JTextField cajaTxtFuncion;
    private javax.swing.JTextField cajaTxtInterA;
    private javax.swing.JTextField cajaTxtInterB;
    private javax.swing.JTextField cajaTxtNumIterPro;
    private javax.swing.JTextField cajaTxtPfijoYflota;
    private javax.swing.JTextField cajaTxtValorProX;
    private javax.swing.JTextField cajaTxt_CW;
    private javax.swing.JTextField cajaTxt_x1;
    private javax.swing.JTextField cajaTxt_x2;
    private javax.swing.JTextField cajaTxt_y1;
    private javax.swing.JTextField cajaTxt_y2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTxtResConv;
    private javax.swing.JTable tableProErro;
    private javax.swing.JTextField txtFuncionST;
    private javax.swing.JTextField txtNTST;
    private javax.swing.JLabel txtPfloatBin;
    private javax.swing.JLabel txtPfloatHexa;
    private javax.swing.JLabel txtResEa;
    private javax.swing.JLabel txtResEr;
    private javax.swing.JLabel txtResExBin;
    private javax.swing.JLabel txtResMan;
    private javax.swing.JLabel txtResPfloatBin;
    private javax.swing.JLabel txtResPfloatHexa;
    private javax.swing.JLabel txtResSigno;
    private javax.swing.JLabel txtResValDeci;
    private javax.swing.JTextField txtXST;
    // End of variables declaration//GEN-END:variables

    private void LimpiarConver() {
        cajaTxt_CW.setText("");
        labelTxtResConv.setText("--");
    }

    private void LimpiarErr() {
        txtResEa.setText("--");
        txtResEr.setText("--");
        cajaTxtErrN1.setText("");
        cajaTxtErrN2.setText("");
    }

    private void LimpiarPuntoFlotante() {
        txtResPfloatBin.setVisible(false);
        txtResPfloatHexa.setVisible(false);
        txtPfloatBin.setVisible(false);
        txtPfloatHexa.setVisible(false);
        txtResSigno.setText("--");
        txtResExBin.setText("--");
        txtResMan.setText("--");
        txtResValDeci.setText("--");
        txtResPfloatBin.setText("--");
        txtResPfloatHexa.setText("--");
        cajaTxtPfijoYflota.setText("");
    }
    private void LimpiarBiseccion() {
        cajaTxtFB.setText("");
        cajaTxtBInteA.setText("");
        cajaTxtBInteB.setText("");
        RespuestaMB.setText("--");
    }
    
    private void LimpiarBolzano() {
        cajaTxtFuncion.setText("");
        cajaTxtInterA.setText("");
        cajaTxtInterB.setText("");
        FuncionXD.setText("--");
    }
    
    private void LimpiarEspMetricos() {
        cajaTxt_x1.setText("");
        cajaTxt_y1.setText("");
        cajaTxt_x2.setText("");
        cajaTxt_y2.setText("");
        Respuesta_Esp.setText("--");
    }
}
