/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.table.DefaultTableModel;
import metodosnumericos.Conversiones;
import metodosnumericos.Errores;
import metodosnumericos.PuntoFlotante;
import metodosnumericos.proErrores;
import metodosnumericos.Biseccion;
import metodosnumericos.Bolzano;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.MathContext;
import java.math.RoundingMode;
import java.util.function.Function;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author pablo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    DefaultTableModel modelo;
    Conversiones Conver = new Conversiones();
    Errores Erro = new Errores();
    PuntoFlotante PuntoF = new PuntoFlotante();
    proErrores proErro = new proErrores();
    Biseccion Bisec = new Biseccion();
    Bolzano Bolza = new Bolzano();

    public Main() {
        initComponents();
        LimpiarConver();
        LimpiarErr();
        txtResPfloatBin.setVisible(false);
        txtResPfloatHexa.setVisible(false);
        txtPfloatBin.setVisible(false);
        txtPfloatHexa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Unidades = new javax.swing.JTabbedPane();
        Unidad1 = new javax.swing.JTabbedPane();
        PanConver = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaTxtConver = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labelTxtBinAdec = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BTcalBinAdec = new javax.swing.JButton();
        BTlimpiarBinAdec = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BTcalDecAbin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        labelTxtDecAbin = new javax.swing.JLabel();
        BTcalOcAdeci = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelTxtOcAdec = new javax.swing.JLabel();
        BTcalHexaAdeci = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        labelTxtHexaAdeci = new javax.swing.JLabel();
        PanErrores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajaTxtErrN1 = new javax.swing.JTextField();
        cajaTxtErrN2 = new javax.swing.JTextField();
        btErrAbs = new javax.swing.JButton();
        btErrRe = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtResEa = new javax.swing.JLabel();
        txtResEr = new javax.swing.JLabel();
        btLimErr = new javax.swing.JButton();
        PunFlotante = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cajaTxtPfijoYflota = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btPflota = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtResSigno = new javax.swing.JLabel();
        txtResExBin = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtResMan = new javax.swing.JLabel();
        txtResValDeci = new javax.swing.JLabel();
        txtPfloatBin = new javax.swing.JLabel();
        txtPfloatHexa = new javax.swing.JLabel();
        txtResPfloatBin = new javax.swing.JLabel();
        txtResPfloatHexa = new javax.swing.JLabel();
        btLimPuntoFloat = new javax.swing.JButton();
        PropaErrores = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cajaTxtValorProX = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cajaTxtNumIterPro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProErro = new javax.swing.JTable();
        btCalcularProErro = new javax.swing.JButton();
        btLimpiarProErro = new javax.swing.JButton();
        Biseccion = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cajaTxtFB = new javax.swing.JTextField();
        cajaTxtBInteA = new javax.swing.JTextField();
        cajaTxtBInteB = new javax.swing.JTextField();
        M_Biseccion = new javax.swing.JButton();
        Limpiar_MBisec = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        RespuestaMB = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Bolzano = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cajaTxtInterA = new javax.swing.JTextField();
        cajaTxtInterB = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        M_Bolzano = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        cajaTxtFuncion = new javax.swing.JTextField();
        FuncionXD = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cajaTxtEps = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        LimpiarMBolza = new javax.swing.JButton();
        Unidad2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("METODOS NÚMERICOS");

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        PanConver.setBackground(new java.awt.Color(255, 255, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("INGRESA EL NUMERO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("RESULTADOS:");

        labelTxtBinAdec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTxtBinAdec.setText("--");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CONVERSIONES");

        BTcalBinAdec.setBackground(new java.awt.Color(153, 255, 153));
        BTcalBinAdec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTcalBinAdec.setText("BINARIO A DECIMAL");
        BTcalBinAdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcalBinAdecActionPerformed(evt);
            }
        });

        BTlimpiarBinAdec.setBackground(new java.awt.Color(153, 255, 153));
        BTlimpiarBinAdec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTlimpiarBinAdec.setText("LIMPIAR");
        BTlimpiarBinAdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTlimpiarBinAdecActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("BINARIO A DECIMAL:");

        BTcalDecAbin.setBackground(new java.awt.Color(153, 255, 153));
        BTcalDecAbin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTcalDecAbin.setText("DECIMAL A BINARIO");
        BTcalDecAbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcalDecAbinActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("DECIMAL A BINARIO:");

        labelTxtDecAbin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTxtDecAbin.setText("--");

        BTcalOcAdeci.setBackground(new java.awt.Color(153, 255, 153));
        BTcalOcAdeci.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTcalOcAdeci.setText("OCTAL A DECIMAL");
        BTcalOcAdeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcalOcAdeciActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("OCTAL A DECIMAL:");

        labelTxtOcAdec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTxtOcAdec.setText("--");

        BTcalHexaAdeci.setBackground(new java.awt.Color(153, 255, 153));
        BTcalHexaAdeci.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTcalHexaAdeci.setText("HEXADECIMAL A DECIMAL");
        BTcalHexaAdeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcalHexaAdeciActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("HEXADECIMAL A DECIMAL:");

        labelTxtHexaAdeci.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTxtHexaAdeci.setText("--");

        javax.swing.GroupLayout PanConverLayout = new javax.swing.GroupLayout(PanConver);
        PanConver.setLayout(PanConverLayout);
        PanConverLayout.setHorizontalGroup(
            PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanConverLayout.createSequentialGroup()
                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanConverLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTxtBinAdec, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTxtDecAbin, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTxtOcAdec, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTxtHexaAdeci, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanConverLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2)
                        .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanConverLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BTcalHexaAdeci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTcalDecAbin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PanConverLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cajaTxtConver, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanConverLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTcalOcAdeci, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTcalBinAdec, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanConverLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTlimpiarBinAdec, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanConverLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanConverLayout.setVerticalGroup(
            PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanConverLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaTxtConver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTcalBinAdec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTcalDecAbin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTcalOcAdeci, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTcalHexaAdeci, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(BTlimpiarBinAdec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtBinAdec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTxtDecAbin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTxtOcAdec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanConverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTxtHexaAdeci, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        Unidad1.addTab("CONVERSIONES", PanConver);

        PanErrores.setBackground(new java.awt.Color(153, 255, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ERRORES");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NUMERO 2:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NUMERO 1:");

        btErrAbs.setBackground(new java.awt.Color(153, 255, 204));
        btErrAbs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btErrAbs.setText("ERROR ABSOLUTO");
        btErrAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErrAbsActionPerformed(evt);
            }
        });

        btErrRe.setBackground(new java.awt.Color(153, 255, 204));
        btErrRe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btErrRe.setText("ERROR RELATIVO");
        btErrRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErrReActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("RESULTADOS:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ERROR ABSOLUTO:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("ERROR RELATIVO:");

        txtResEa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtResEa.setText("--");

        txtResEr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtResEr.setText("--");

        btLimErr.setBackground(new java.awt.Color(153, 255, 204));
        btLimErr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimErr.setText("LIMPIAR");
        btLimErr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimErrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanErroresLayout = new javax.swing.GroupLayout(PanErrores);
        PanErrores.setLayout(PanErroresLayout);
        PanErroresLayout.setHorizontalGroup(
            PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanErroresLayout.createSequentialGroup()
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanErroresLayout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(btErrAbs)
                            .addGap(45, 45, 45)
                            .addComponent(btErrRe, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanErroresLayout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanErroresLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cajaTxtErrN2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanErroresLayout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cajaTxtErrN1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanErroresLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResEa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanErroresLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResEr, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btLimErr, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        PanErroresLayout.setVerticalGroup(
            PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanErroresLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaTxtErrN1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaTxtErrN2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btErrAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btErrRe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btLimErr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResEa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResEr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        Unidad1.addTab("ERRORES", PanErrores);

        PunFlotante.setBackground(new java.awt.Color(255, 204, 204));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("PUNTO FIJO Y FLOTANTE");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Ingresa el valor:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("RESPUESTAS:");

        btPflota.setBackground(new java.awt.Color(255, 102, 102));
        btPflota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPflota.setText("CALCULAR");
        btPflota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPflotaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("SIGNO:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("EXPONENTE (BINARIO):");

        txtResSigno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResSigno.setText("--");

        txtResExBin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResExBin.setText("--");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("MANTIZA (BINARIO):");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("VALOR DECIMAL:");

        txtResMan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResMan.setText("--");

        txtResValDeci.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResValDeci.setText("--");

        txtPfloatBin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPfloatBin.setText("VALOR BINARIO:");

        txtPfloatHexa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPfloatHexa.setText("VALOR HEXADECIMAL:");

        txtResPfloatBin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResPfloatBin.setText("--");

        txtResPfloatHexa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResPfloatHexa.setText("--");

        btLimPuntoFloat.setBackground(new java.awt.Color(255, 102, 102));
        btLimPuntoFloat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimPuntoFloat.setText("LIMPIAR");
        btLimPuntoFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimPuntoFloatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PunFlotanteLayout = new javax.swing.GroupLayout(PunFlotante);
        PunFlotante.setLayout(PunFlotanteLayout);
        PunFlotanteLayout.setHorizontalGroup(
            PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PunFlotanteLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txtResMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(txtPfloatHexa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResPfloatHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(txtPfloatBin)
                                .addGap(18, 18, 18)
                                .addComponent(txtResPfloatBin, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel17))
                                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtResSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(txtResValDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(txtResExBin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PunFlotanteLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btPflota, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btLimPuntoFloat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PunFlotanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(32, 32, 32)
                        .addComponent(cajaTxtPfijoYflota, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(185, 185, 185))
        );
        PunFlotanteLayout.setVerticalGroup(
            PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PunFlotanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaTxtPfijoYflota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPflota, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimPuntoFloat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel17)
                .addGap(36, 36, 36)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResExBin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResMan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResValDeci))
                .addGap(12, 12, 12)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPfloatBin, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtResPfloatBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPfloatHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResPfloatHexa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        Unidad1.addTab("P.FLOTANTE Y FLOTANTE", PunFlotante);

        PropaErrores.setBackground(new java.awt.Color(204, 204, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("PROPAGACION DE ERRORES");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Ingresa el valor de \"X\":");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Ingresa el numero de iteraciones:");

        tableProErro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteracion", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProErro);

        btCalcularProErro.setText("CALCULAR");
        btCalcularProErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularProErroActionPerformed(evt);
            }
        });

        btLimpiarProErro.setText("LIMPIAR");
        btLimpiarProErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarProErroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PropaErroresLayout = new javax.swing.GroupLayout(PropaErrores);
        PropaErrores.setLayout(PropaErroresLayout);
        PropaErroresLayout.setHorizontalGroup(
            PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropaErroresLayout.createSequentialGroup()
                .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaTxtValorProX)
                            .addComponent(cajaTxtNumIterPro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btCalcularProErro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btLimpiarProErro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PropaErroresLayout.setVerticalGroup(
            PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropaErroresLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cajaTxtValorProX, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cajaTxtNumIterPro, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCalcularProErro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpiarProErro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        Unidad1.addTab("PROPAGACION ERRORES", PropaErrores);

        Biseccion.setBackground(new java.awt.Color(153, 255, 204));

        jLabel36.setText("Ingrese la función:");

        jLabel29.setText("Ingrese el límite inferior del intervalo (a):");

        jLabel30.setText("Ingrese el límite superior del intervalo (b):");

        M_Biseccion.setText("CALCULAR");
        M_Biseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BiseccionActionPerformed(evt);
            }
        });

        Limpiar_MBisec.setText("LIMPIAR");
        Limpiar_MBisec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_MBisecActionPerformed(evt);
            }
        });

        jLabel31.setText("La raíz se encuentra en x = ");

        RespuestaMB.setText("Respuesta");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setText("METODO BISECCION");

        javax.swing.GroupLayout BiseccionLayout = new javax.swing.GroupLayout(Biseccion);
        Biseccion.setLayout(BiseccionLayout);
        BiseccionLayout.setHorizontalGroup(
            BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiseccionLayout.createSequentialGroup()
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BiseccionLayout.createSequentialGroup()
                                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel36))
                                .addGap(79, 79, 79)
                                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cajaTxtFB, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(cajaTxtBInteA)
                                    .addComponent(cajaTxtBInteB)))
                            .addComponent(jLabel33)))
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addComponent(M_Biseccion))
                        .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BiseccionLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Limpiar_MBisec))
                            .addGroup(BiseccionLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(RespuestaMB)))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        BiseccionLayout.setVerticalGroup(
            BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BiseccionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel33)
                .addGap(50, 50, 50)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cajaTxtFB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(cajaTxtBInteA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(cajaTxtBInteB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_Biseccion)
                    .addComponent(Limpiar_MBisec))
                .addGap(71, 71, 71)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(RespuestaMB))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        Unidad1.addTab("BISECCION", Biseccion);

        Bolzano.setBackground(new java.awt.Color(51, 255, 0));

        jLabel25.setText("Ingrese el extremo izquierdo del intervalo:");

        jLabel26.setText("Ingrese el extremo derecho del intervalo:");

        cajaTxtInterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTxtInterAActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("METODO DE BOLZNO");

        M_Bolzano.setText("INGRESAR DATOS");
        M_Bolzano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BolzanoActionPerformed(evt);
            }
        });

        jLabel28.setText("Ingrese la función (utilice 'x' como variable):");

        jLabel32.setText("Ingrese la precisión deseada:");

        jLabel34.setText("La aproximación de la solución es:");

        LimpiarMBolza.setText("LIMPIAR");
        LimpiarMBolza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarMBolzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BolzanoLayout = new javax.swing.GroupLayout(Bolzano);
        Bolzano.setLayout(BolzanoLayout);
        BolzanoLayout.setHorizontalGroup(
            BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BolzanoLayout.createSequentialGroup()
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel27))
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BolzanoLayout.createSequentialGroup()
                                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel26)
                                    .addGroup(BolzanoLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel32))
                                    .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(M_Bolzano)
                                        .addComponent(jLabel25)))
                                .addGap(56, 56, 56)
                                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cajaTxtInterA, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaTxtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaTxtInterB, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaTxtEps, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(BolzanoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BolzanoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LimpiarMBolza, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FuncionXD, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );
        BolzanoLayout.setVerticalGroup(
            BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BolzanoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel27)
                .addGap(37, 37, 37)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cajaTxtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cajaTxtInterA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(cajaTxtInterB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32)
                    .addComponent(cajaTxtEps, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_Bolzano)
                    .addComponent(LimpiarMBolza))
                .addGap(59, 59, 59)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FuncionXD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        Unidad1.addTab("BOLZANO", Bolzano);

        Unidades.addTab("UNIDAD 1", Unidad1);

        javax.swing.GroupLayout Unidad2Layout = new javax.swing.GroupLayout(Unidad2);
        Unidad2.setLayout(Unidad2Layout);
        Unidad2Layout.setHorizontalGroup(
            Unidad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        Unidad2Layout.setVerticalGroup(
            Unidad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        Unidades.addTab("UNIIDAD 2", Unidad2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTcalBinAdecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcalBinAdecActionPerformed
        // TODO add your handling code here:
        String BinAdeci = cajaTxtConver.getText();
        Conver.BinarioAdecimal(BinAdeci);

        labelTxtBinAdec.setText(String.valueOf(Conver.BinarioAdecimal(BinAdeci)));
    }//GEN-LAST:event_BTcalBinAdecActionPerformed

    private void BTlimpiarBinAdecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTlimpiarBinAdecActionPerformed
        // TODO add your handling code here:
        LimpiarConver();
    }//GEN-LAST:event_BTlimpiarBinAdecActionPerformed

    private void BTcalDecAbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcalDecAbinActionPerformed
        // TODO add your handling code here:
        double deciAbin = 0;
        deciAbin = Double.parseDouble(cajaTxtConver.getText());
        int PartEntera = (int) deciAbin;
        double PartFrac = deciAbin - PartEntera;

        String PartEnteraBinaria = Integer.toBinaryString(PartEntera);
        String PartFactBinaria = Conver.DecimalAbinario(PartFrac);

        String NumeroBinario = PartEnteraBinaria + "." + PartFactBinaria;

        labelTxtDecAbin.setText(String.valueOf(NumeroBinario));
    }//GEN-LAST:event_BTcalDecAbinActionPerformed

    private void BTcalOcAdeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcalOcAdeciActionPerformed
        // TODO add your handling code here:
        String octalAdeci = cajaTxtConver.getText();
        Conver.OctalAdecimal(octalAdeci);

        labelTxtOcAdec.setText(String.valueOf(Conver.OctalAdecimal(octalAdeci)));
    }//GEN-LAST:event_BTcalOcAdeciActionPerformed

    private void BTcalHexaAdeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcalHexaAdeciActionPerformed
        // TODO add your handling code here:
        String HexaAdeci = cajaTxtConver.getText();

        int decimal = Integer.parseInt(HexaAdeci, 16);

        labelTxtHexaAdeci.setText(String.valueOf(decimal));
    }//GEN-LAST:event_BTcalHexaAdeciActionPerformed

    private void btErrReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErrReActionPerformed
        // TODO add your handling code here:
        double err1 = 0, err2 = 0, Ea = 0;
        err2 = Double.parseDouble(cajaTxtErrN2.getText());
        err1 = Double.parseDouble(cajaTxtErrN1.getText());
        Ea = Erro.errAbs(err1, err2);
        txtResEr.setText(String.valueOf(Erro.errRel(Ea, err2)));
    }//GEN-LAST:event_btErrReActionPerformed

    private void btErrAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErrAbsActionPerformed
        // TODO add your handling code here:
        double err1 = 0, err2 = 0;
        err1 = Double.parseDouble(cajaTxtErrN1.getText());
        err2 = Double.parseDouble(cajaTxtErrN2.getText());

        txtResEa.setText(String.valueOf(Erro.errAbs(err1, err2)));

    }//GEN-LAST:event_btErrAbsActionPerformed

    private void btLimErrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimErrActionPerformed
        // TODO add your handling code here:
        LimpiarErr();
    }//GEN-LAST:event_btLimErrActionPerformed

    private void btPflotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPflotaActionPerformed
        // TODO add your handling code here:
        String Pfloat = "";

        Pfloat = cajaTxtPfijoYflota.getText();
        boolean verdad = PuntoF.verficarHexa(Pfloat);

        if (verdad == true) {

            txtResPfloatBin.setVisible(false);
            txtResPfloatHexa.setVisible(false);
            txtPfloatBin.setVisible(false);
            txtPfloatHexa.setVisible(false);

            int PfloatEntero = Integer.parseInt(Pfloat.substring(2), 16);
            int signo = (PfloatEntero >> 31) & 1;
            int exponente = ((PfloatEntero >> 23) & 0xFF);
            int mantisa = PfloatEntero & 0x7FFFFF;

            String mantisaBinaria = String.format("%23s", Integer.toBinaryString(mantisa)).replace(' ', '0');
            String exponenteBinario = String.format("%8s", Integer.toBinaryString(exponente)).replace(' ', '0');

            double valor = Math.pow(-1, signo) * (1 + (mantisa / Math.pow(2, 23))) * Math.pow(2, exponente - 127);

            txtResSigno.setText(String.valueOf(signo));
            txtResExBin.setText(String.valueOf(exponenteBinario));
            txtResMan.setText(String.valueOf(mantisaBinaria));
            txtResValDeci.setText(String.valueOf(valor));

        } else {

            txtResPfloatBin.setVisible(true);
            txtResPfloatHexa.setVisible(true);
            txtPfloatBin.setVisible(true);
            txtPfloatHexa.setVisible(true);

            float ValDeci = 0f;
            ValDeci = Float.parseFloat(cajaTxtPfijoYflota.getText());

            int bits = Float.floatToIntBits(ValDeci);
            int signo = (bits >> 31) & 1;
            int exponente = (bits >> 23) & 0xFF;
            int mantisa = bits & 0x7FFFFF;

            String mantisaBinaria = String.format("%23s", Integer.toBinaryString(mantisa)).replace(' ', '0');
            String exponenteBinario = String.format("%8s", Integer.toBinaryString(exponente)).replace(' ', '0');
            String valorBinario = String.format("%32s", Integer.toBinaryString(bits)).replace(' ', '0');
            String valorHexa = String.format("%8s", Integer.toHexString(bits)).replace(' ', '0').toUpperCase();

            float valor = (float) ((Math.pow(-1, signo) * (1 + (mantisa / Math.pow(2, 23)))) * Math.pow(2, exponente - 127));

            txtResSigno.setText(String.valueOf(signo));
            txtResExBin.setText(String.valueOf(exponenteBinario));
            txtResMan.setText(String.valueOf(mantisaBinaria));
            txtResValDeci.setText(String.valueOf(valor));
            txtResPfloatBin.setText(String.valueOf(valorBinario));
            txtResPfloatHexa.setText(String.valueOf("0X" + valorHexa));
        }


    }//GEN-LAST:event_btPflotaActionPerformed

    private void btLimPuntoFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimPuntoFloatActionPerformed
        // TODO add your handling code here:
        LimpiarPuntoFlotante();
    }//GEN-LAST:event_btLimPuntoFloatActionPerformed

    private void btCalcularProErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularProErroActionPerformed
        // TODO add your handling code here:
        try {
            modelo = (DefaultTableModel) this.tableProErro.getModel();

            String valXproErro = cajaTxtValorProX.getText();
            BigDecimal valBigPro = new BigDecimal(valXproErro);
            int IterProErro = Integer.parseInt(cajaTxtNumIterPro.getText());

            XYDataset data = proErro.createDataset(valBigPro, IterProErro);
            JFreeChart chart = proErro.createChart(data);

            ChartFrame frame = new ChartFrame("PROPAGACION DE ERRORES", chart);
            frame.pack();
            frame.setVisible(true);
            //tabla
            for (int i = 1; i <= IterProErro; i++) {
                BigDecimal numerator = proErro.exp(valBigPro, i);
                BigDecimal denominator = proErro.exp(valBigPro, i).subtract(BigDecimal.ONE);
                BigDecimal result = numerator.divide(denominator, 128, RoundingMode.HALF_UP);

                Object datosProErro[] = new Object[]{i, result.toString()};
                modelo.addRow(datosProErro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"NO HAY DATOS EN EL PROGRAMA");
        }

    }//GEN-LAST:event_btCalcularProErroActionPerformed

    private void btLimpiarProErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarProErroActionPerformed
        // TODO add your handling code here:
        cajaTxtNumIterPro.setText("");
        cajaTxtValorProX.setText("");
        modelo.getDataVector().removeAllElements();
        tableProErro.updateUI();
    }//GEN-LAST:event_btLimpiarProErroActionPerformed

    private void M_BiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BiseccionActionPerformed
        // TODO add your handling code here:
        double InterB_A = Double.parseDouble(cajaTxtBInteA.getText());
        double InterB_B = Double.parseDouble(cajaTxtBInteB.getText());
        String functionStr = cajaTxtFB.getText();

        Function<Double, Double> funcionB;
        funcionB = Bisec.CrearFuncionB(functionStr);
        double xD = Bisec.findRoot(InterB_A, InterB_B, funcionB);
        Bisec.evaluarFuncion(functionStr, xD);
        RespuestaMB.setText(String.valueOf(Bisec.findRoot(InterB_A, InterB_B, funcionB)));
    }//GEN-LAST:event_M_BiseccionActionPerformed

    private void Limpiar_MBisecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_MBisecActionPerformed
        // TODO add your handling code here:
        LimpiarBiseccion();
    }//GEN-LAST:event_Limpiar_MBisecActionPerformed

    private void cajaTxtInterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTxtInterAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTxtInterAActionPerformed

    private void M_BolzanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BolzanoActionPerformed
        // TODO add your handling code here:
        double InterA = Double.parseDouble(cajaTxtInterA.getText());
        double InterB = Double.parseDouble(cajaTxtInterB.getText());
        double Eps = Double.parseDouble(cajaTxtEps.getText());
        String funcionString = cajaTxtFuncion.getText();

        Function<Double, Double> funcion;
        funcion = Bolza.CrearFuncion(funcionString);

        double valorX = Bolza.EncontrarAproximacion(funcion, InterA, InterB, Eps);
        Bolza.EvaluarFuncion(funcionString,valorX);
        FuncionXD.setText(String.valueOf(Bolza.EncontrarAproximacion(funcion, InterA, InterB, Eps)));
    }//GEN-LAST:event_M_BolzanoActionPerformed

    private void LimpiarMBolzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarMBolzaActionPerformed
        // TODO add your handling code here:
        LimpiarBolzano();
    }//GEN-LAST:event_LimpiarMBolzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTcalBinAdec;
    private javax.swing.JButton BTcalDecAbin;
    private javax.swing.JButton BTcalHexaAdeci;
    private javax.swing.JButton BTcalOcAdeci;
    private javax.swing.JButton BTlimpiarBinAdec;
    private javax.swing.JPanel Biseccion;
    private javax.swing.JPanel Bolzano;
    private javax.swing.JLabel FuncionXD;
    private javax.swing.JButton LimpiarMBolza;
    private javax.swing.JButton Limpiar_MBisec;
    private javax.swing.JButton M_Biseccion;
    private javax.swing.JButton M_Bolzano;
    private javax.swing.JPanel PanConver;
    private javax.swing.JPanel PanErrores;
    private javax.swing.JPanel PropaErrores;
    private javax.swing.JPanel PunFlotante;
    private javax.swing.JLabel RespuestaMB;
    private javax.swing.JTabbedPane Unidad1;
    private javax.swing.JPanel Unidad2;
    private javax.swing.JTabbedPane Unidades;
    private javax.swing.JButton btCalcularProErro;
    private javax.swing.JButton btErrAbs;
    private javax.swing.JButton btErrRe;
    private javax.swing.JButton btLimErr;
    private javax.swing.JButton btLimPuntoFloat;
    private javax.swing.JButton btLimpiarProErro;
    private javax.swing.JButton btPflota;
    private javax.swing.JTextField cajaTxtBInteA;
    private javax.swing.JTextField cajaTxtBInteB;
    private javax.swing.JTextField cajaTxtConver;
    private javax.swing.JTextField cajaTxtEps;
    private javax.swing.JTextField cajaTxtErrN1;
    private javax.swing.JTextField cajaTxtErrN2;
    private javax.swing.JTextField cajaTxtFB;
    private javax.swing.JTextField cajaTxtFuncion;
    private javax.swing.JTextField cajaTxtInterA;
    private javax.swing.JTextField cajaTxtInterB;
    private javax.swing.JTextField cajaTxtNumIterPro;
    private javax.swing.JTextField cajaTxtPfijoYflota;
    private javax.swing.JTextField cajaTxtValorProX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTxtBinAdec;
    private javax.swing.JLabel labelTxtDecAbin;
    private javax.swing.JLabel labelTxtHexaAdeci;
    private javax.swing.JLabel labelTxtOcAdec;
    private javax.swing.JTable tableProErro;
    private javax.swing.JLabel txtPfloatBin;
    private javax.swing.JLabel txtPfloatHexa;
    private javax.swing.JLabel txtResEa;
    private javax.swing.JLabel txtResEr;
    private javax.swing.JLabel txtResExBin;
    private javax.swing.JLabel txtResMan;
    private javax.swing.JLabel txtResPfloatBin;
    private javax.swing.JLabel txtResPfloatHexa;
    private javax.swing.JLabel txtResSigno;
    private javax.swing.JLabel txtResValDeci;
    // End of variables declaration//GEN-END:variables

    private void LimpiarConver() {
        cajaTxtConver.setText("");
        labelTxtBinAdec.setText("--");
        labelTxtDecAbin.setText("--");
        labelTxtOcAdec.setText("--");
        labelTxtHexaAdeci.setText("--");

    }

    private void LimpiarErr() {
        txtResEa.setText("--");
        txtResEr.setText("--");
        cajaTxtErrN1.setText("");
        cajaTxtErrN2.setText("");
    }

    private void LimpiarPuntoFlotante() {
        txtResPfloatBin.setVisible(false);
        txtResPfloatHexa.setVisible(false);
        txtPfloatBin.setVisible(false);
        txtPfloatHexa.setVisible(false);
        txtResSigno.setText("--");
        txtResExBin.setText("--");
        txtResMan.setText("--");
        txtResValDeci.setText("--");
        txtResPfloatBin.setText("--");
        txtResPfloatHexa.setText("--");
        cajaTxtPfijoYflota.setText("");
    }
    private void LimpiarBiseccion() {
        cajaTxtFB.setText("");
        cajaTxtBInteA.setText("");
        cajaTxtBInteB.setText("");
        RespuestaMB.setText("--");
    }
    
    private void LimpiarBolzano() {
        cajaTxtFuncion.setText("");
        cajaTxtInterA.setText("");
        cajaTxtInterB.setText("");
        cajaTxtEps.setText("");
        FuncionXD.setText("--");
    }
}
